### ISSUE TITLE
React 18 support

### ISSUE THREAD

**Issue by dmorda** [antokara/react-recaptcha-x#103]
I was installing this in a project that uses Gatsby and React 18. Got the following message during npm install.

```
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.6.0 || ^17.0.0" from react-recaptcha-x@1.1.13
npm ERR! node_modules/react-recaptcha-x
npm ERR!   react-recaptcha-x@"^1.1.13" from the root project
```

Any chance of React 18 support soon?

**Comment by antokara** [comment]
@AlexKarajohn please add support

**Comment by antokara** [comment]
@dmorda , support for React 18.x was just added with #104 by @AlexKarajohn .

Please let us know if you have any issues with the latest release and/or React 18 support.
Thank you!

**Comment by dmorda** [comment]
Awesome, thanks for the update @antokara!
