### ISSUE TITLE
prop that can re-generate a token

### ISSUE THREAD

**Issue by morcoteg** [antokara/react-recaptcha-x#19]
When I use the `ReCaptchaV3` component, I noticed that the component (or page, in my case) needs to re-render in order for a token to be regenerated. If that is true, continue reading, otherwise, I overlooked something, so feel free to close this :)

It would be nice to have an option, or a callback, something, that would allow the component to regenerate a token (maybe when a condition becomes true, or some custom callback defines this behavior).
```
<RecaptchaV3
   ...
  regenerateToken={boolean || callback}
   ...
/>
```

For now, I'm reloading the page after the form submits, to regenerate the token.

**Comment by antokara** [comment]
Hello @morcoteg and thanks for opening an issue with your feature/request idea.

Can you please help me understand when you need this?

Is it when the current token expired/failed after the server validation failed or simply when you need to re-use it for a new form/action?

I have a couple of ideas on how to tackle it:

1. I want in the near future, to introduce react hooks for it and one hook can do exactly that
2. create a HOC like redux-connect, which will provide the prop required to re-generate
3. use the current callback function, to provide an event function, which can be deferred and used when you want to regenerate the token

Please let me know your use-case and thoughts.
Thank you for your time.

**Comment by morcoteg** [comment]
It would be after the current token has been already used (it could be when it expired also, or other use cases you could think of). This is non-urgent, so it's not time sensitive :)

Our use case is that after the form submits, a confirmation modal appears, then after clicking "OK", we just clear the props populating the form so another request can be made, without reloading the page. I had to reload the page though to get the RecaptchaV3 component to generate a new token to use to verify the user's theoretical 2nd request.

**Comment by antokara** [comment]
@morcoteg I just release v1.1.0 which supports it for the v3.

I didn't add it to the v2 component because it somewhat requires a complete re-render of the Google reCaptcha v2 widget to retrieve a new token and can be achieved easily by simply hiding / showing the component once. 

The same thing could also be achieved on the v3 but since that one is not visible, it made more sense to add a function for it.

ie.
```js
{visible && (<ReCaptchaV2
            callback={this.v2CallbackB}
            theme={EReCaptchaV2Theme.Dark}
            size={EReCaptchaV2Size.Compact}
            tabindex={0}
/>)}
{visible && <ReCaptchaV3 action="actionB" callback={this.v3CallbackB} />}
```
(set visible:false and then visible:true, to cause a re-render of just the component)

Please let me know if the new feature works for you and if there are any questions.
Thanks!

**Comment by morcoteg** [comment]
Ah, very nice! How would we use the new prop? I notice in the example above, there isn't a new prop, is it supposed to be built into `v3CallbackB` in this example?

**Comment by antokara** [comment]
It's in the callback of the v3 component.

You can check the readme examples:
https://github.com/antokara/react-recaptcha-x#simple-javascript-example

or even the code examples included for its use:
https://github.com/antokara/react-recaptcha-x/blob/master/examples/typescript/index.tsx

**Comment by antokara** [comment]
@morcoteg If everything works and you like the project, please consider giving it a star in github.
Thanks!
