### ISSUE TITLE
Return type of execute() is not a Promise

### ISSUE THREAD

**Issue by alreece45** [antokara/react-recaptcha-x#34]
**Describe the bug**
The return type of grecaptcha.execute() is not a Promise, but a PromiseLike (it only has a then function).

**To Reproduce**
1. Run `console.log(grecaptcha.execute(siteKeyV3, { action })`
2. See an object with only `then()` returned

**Expected behavior**
Represent actual return type

**Comment by antokara** [comment]
thank you @alreece45 for improving the types as well!

please considering giving this project a star, if you have found it useful.
