### ISSUE TITLE
useState hook example for functional component

### ISSUE THREAD

**Issue by dmorda** [antokara/react-recaptcha-x#40]
I love the simplicity and was able to get it working in a functional component or so I thought. Although it worked, it kept refreshing the token non-stop and despite my troubleshooting I've not been able to figure out the best way to get this working.

Included below is my component and if you view the console log, you will notice it continues to refresh the token every few milliseconds due to the "setCaptchaRefreshToken(refreshToken)" call...but I'm not sure how else to do that.

Would love it if you could include an example of how to get it working using a functional component with the useState hook. Thanks in advance!

```// Node modules
import React, { useState } from "react"
import { ReCaptchaV3 } from 'react-recaptcha-x'

const NewsletterForm = props => {

  // Holds captcha token
  const [captchaToken, setCaptchaToken] = useState(null)

  // Hold captcha retrieval status
  const [captchaRetrieving, setCaptchaRetrieving] = useState(false)

  // Hold captcha refresh function
  const [captchaRefreshToken, setCaptchaRefreshToken] = useState(null)

  // Callback method for the react-recaptcha-x
  const v3Callback = (token, refreshToken) => {
    if (typeof token === 'string') {
      setCaptchaToken(token)
      setCaptchaRetrieving(false)
      setCaptchaRefreshToken(refreshToken)
      console.log('v3Callback: it is a string')
    } else {
      // retrieval in progress
      setCaptchaRetrieving(true)
      console.log('v3Callback: retrieval in progress')
    }
  }

  return (
    <div>
      <ReCaptchaV3 action="newsletterSignup" callback={v3Callback} />
    </div>
  )
}

export default NewsletterForm
```

**Comment by antokara** [comment]
hello @dmorda ,

I am glad you find this component useful!
Hooks have a few subtle differences than Class Components.

One of which, is storing a function in the State.
I found this helpful article that explains the issue and the solutions:
https://medium.com/swlh/how-to-store-a-function-with-the-usestate-hook-in-react-8a88dd4eede1

Basically, you have to change
```js
setCaptchaRefreshToken(refreshToken)
```
to
```js
setCaptchaRefreshToken(() => refreshToken)
```

Please close this issue, if the solution works for you.
I will probably include documentation and/or a demo of Functional Components with Hooks, in the next release of the component, to help others with the same issue...

Thank you for reporting/asking this and please consider giving a :star: to the project.

**Comment by dmorda** [comment]
Worked like a charm, thanks for the pointer!
