### ISSUE TITLE
Peer dependency conflict with react 17 and 16

### ISSUE THREAD

**Issue by dmorda** [antokara/react-recaptcha-x#61]
**Describe the bug**
When I run `npm install react-recaptcha-x` I get an error indicating an upstream dependency conflict. I'm doing this in a fresh Gatsby v3 project that includes "react ^17.0.2" in the package.json.

**To Reproduce**
1. Setup a new Gatsby v3 project
2. Open a terminal and run "npm install react-recaptcha-x"
3. See error

```
$ npm install react-recaptcha-x --save
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: my-cool-website@1.0.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.6.0" from react-recaptcha-x@1.1.11
npm ERR! node_modules/react-recaptcha-x
npm ERR!   react-recaptcha-x@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/xyz/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xyz/.npm/_logs/2021-04-07T16_41_39_330Z-debug.log
```

**Expected behavior**
Package installs successfully.

**Desktop (please complete the following information):**
 - OS: macOS 11.2.3
 - Browser: Not applicable
 - Version: Not applicable

**Comment by antokara** [comment]
Hello @dmorda!

Thank for reporting this.

I just released version 1.1.12 which should fix the issue.
Please reopen the ticket, if the problem persists.
