### ISSUE TITLE
Typing issues with paths on imports

### ISSUE THREAD

**Issue by mike-jewell** [antokara/react-recaptcha-x#9]
I'm having build issues with the supplied typings:

ERROR in node_modules/react-recaptcha-x/dist/reCaptchaV2/container/ReCaptchaV2.d.ts(2,24):
TS2307: Cannot find module 'src/reCaptchaV2/component/IProps'.

ERROR in node_modules/react-recaptcha-x/dist/reCaptchaV3/container/ReCaptchaV3.d.ts(2,24):
TS2307: Cannot find module 'src/reCaptchaV3/component/IProps'.

The issue is the path, it references:

src/reCaptchaV2/component/IProps

instead of:

../component/IProps

I'm not sure why this is, could be the use of a baseUrl and paths impacting the build.

Once I manually change the typings in the node_modules it works great.  Thanks for the library.

**Comment by antokara** [comment]
Hello Mike and thank you for the comments, merge request and kind words. Unfortunately, I've been really busy since the last release but I plan to get back at it within the following days. I want first to reproduce the issue you're having because I didn't have that experience in my tests. I'll keep you posted and I'll review your PR as well once I'm done. Thanks again.

**Comment by antokara** [comment]
@mike-jewell can you please provide the steps to reproduce this or a codesandbox.io demo that shows the issue?

I have here both JS and TS examples and they work without failures or warnings (you need to set your site key of course)

https://codesandbox.io/embed/v2-javascript-example-m10wk
https://codesandbox.io/embed/v2-typescript-example-1obrg

I also just released v1.0.5 with the packages update / security fixes.

**Comment by mike-jewell** [comment]
@antokara I have just committed the following:

https://github.com/mike-jewell/react-recaptcha-x/commit/3e722edff8d39893baf2a7b85990ad9cbaa1d676

The issue is the use of fork-ts-checker-webpack-plugin as a part of the build process.  We use this for performance and more checks which helps catch this kind of thing.  Hope that helps and doesn't conflict for you...

**Comment by antokara** [comment]
@mike-jewell thank you. I was able to reproduce and got the following:

```
no-use-before-declare is deprecated. Since TypeScript 2.9. Please use the built-in compiler checks instead.
Warning: no-function-constructor-with-string-args rule is deprecated. Replace your usage with the TSLint function-constructor rule.
Warning: no-reserved-keywords rule is deprecated. Replace your usage with the TSLint variable-name rule.
Warning: no-increment-decrement rule is deprecated. Replace your usage with the TSLint increment-decrement rule.
Warning: no-unnecessary-bind rule is deprecated. Replace your usage with the TSLint unnecessary-bind rule.
ERROR in /home/user/Projects/react-recaptcha-v3-v2/examples/typescript/index.tsx(32,24):
no-unsafe-any: Unsafe use of expression of type 'any'.
ERROR in /home/user/Projects/react-recaptcha-v3-v2/examples/typescript/index.tsx(33,24):
no-unsafe-any: Unsafe use of expression of type 'any'.
ERROR in /home/user/Projects/react-recaptcha-v3-v2/examples/typescript/index.tsx(34,24):
no-unsafe-any: Unsafe use of expression of type 'any'.
ERROR in /home/user/Projects/react-recaptcha-v3-v2/examples/typescript/index.tsx(35,24):
no-unsafe-any: Unsafe use of expression of type 'any'.
ERROR in /home/user/Projects/react-recaptcha-v3-v2/dist/reCaptchaV2/container/ReCaptchaV2.d.ts(2,24):
TS2307: Cannot find module 'src/reCaptchaV2/component/IProps'.
ERROR in /home/user/Projects/react-recaptcha-v3-v2/dist/reCaptchaV3/container/ReCaptchaV3.d.ts(2,24):
TS2307: Cannot find module 'src/reCaptchaV3/component/IProps'.
```

I think I forgot in my TS example to switch from `babel-loader` + `@babel/preset-typescript` to `ts-loader` and `babel-loader` is more forgiving... I will do the loader switch for more strict TS checks and follow up on your issue.

**Comment by antokara** [comment]
@mike-jewell please try v1.0.6 and re-open if the issue persists...

I plan to fix the other (non blocking I hope) issues:
```
ERROR in /home/user/Projects/react-recaptcha-v3-v2/examples/typescript/index.tsx(32,24):
no-unsafe-any: Unsafe use of expression of type 'any'.
ERROR in /home/user/Projects/react-recaptcha-v3-v2/examples/typescript/index.tsx(33,24):
no-unsafe-any: Unsafe use of expression of type 'any'.
ERROR in /home/user/Projects/react-recaptcha-v3-v2/examples/typescript/index.tsx(34,24):
no-unsafe-any: Unsafe use of expression of type 'any'.
ERROR in /home/user/Projects/react-recaptcha-v3-v2/examples/typescript/index.tsx(35,24):
no-unsafe-any: Unsafe use of expression of type 'any'.
```
in a future release.

Thank you!

**Comment by antokara** [comment]
For reference, relative to the issue that was causing it and other solutions:
https://github.com/microsoft/TypeScript/issues/21507
https://github.com/Microsoft/TypeScript/issues/23701
https://github.com/microsoft/TypeScript/issues/15479

**Comment by mike-jewell** [comment]
Thanks for this.  Working perfectly now.
