### ISSUE TITLE
TypeError: Cannot destructure property 'siteKeyV3' of 'this.props.providerContext' as it is undefined.

### ISSUE THREAD

**Issue by sphantom99** [antokara/react-recaptcha-x#98]
**Describe the bug**
Hello, I'm trying to use this library for a nextjs app. When I build and run the project the server responds with an internal server error giving the above error output. 

**To Reproduce**
Set up a nextjs 12 project, install the library and try to build and run

**Comment by antokara** [comment]
Hello @sphantom99 can you please provide an online repository with the reproducible issue that I can test with?

**Comment by sphantom99** [comment]
Hello and thanks for the reply! I have set up the same situation here: https://github.com/sphantom99/recaptcha-test
But now I'm getting a different error, Error: The prop "siteKeyV3" must be set on the ReCaptchaProvider before using the ReCaptchaV3 component.

**Comment by antokara** [comment]
@sphantom99, I will try to take a look at your code this weekend and get back to you

**Comment by AlexKarajohn** [comment]
@sphantom99, after looking into this issue it seems that this package is not compatible with nextjs.

In the following week I will investigate why this is the case.

**Comment by AlexKarajohn** [comment]
@sphantom99 as per documentation ' <ReCaptchaV3 action="actionA" callback={v3Callback} />' requires action and callback. 

The siteKeyV3 should only be provided in the Provider. This fixes the issue

**Comment by antokara** [comment]
@sphantom99 I'm closing the issue as resolved. Please comment if that didn't solve your issue, so I can reopen it.
